- name: "subir apache"
  hosts: master-node

  tasks:
  - name: update
    shell: apt-get update -y
    register: apt-atualiza

  - name: subir-apache
    apt: name=apache2 state=present

  - name: subir mysql e php-mysql
    apt: name={{item}} state=latest
    with_items:
      - mysql-server
      #- php5-mysql

  - name: subir php
    apt: name{{ item }} state=installed update_cache=yes
    with_items:
      - php
      - libapache2-mod-php
     # - php-mysql
     # - php5
     # - libapache2-mod-php5
     # - php5-mcrypt
     # - php5-cli
     # - php5-dev
     # - php5-curl
     # - php5-gd
     # - git
     # - mcrypt
     # - nginx
     # - php5-cli
     # - php5-curl
     # - php5-fpm
     # - php5-intl
     # - php5-json
      - php5-mcrypt
     # - php5-sqlite
     # - sqlite3

#  - name: ensure php5-fpm cgi.fix_pathinfo=0
  #  lineinfile: dest=/etc/php5/fpm/php.ini regexp='^(.*)cgi.fix_pathinfo=' line=cgi.fix_pathinfo=0

 # - name: habilitar php
 #   shell: a2enmod php5

  - name: copia-vhost
    copy: src=../files/meuwebsite.conf dest=/etc/apache2/sites-enabled/000-default.conf

  #- name: apaga index
  #  shell: rm -r /var/www/html/index.html

  - name: copia-info
    copy: src=../files/info.php dest=/var/www/html/info.php
    notify:
    - reinicia apache

  - name: hab-php
    shell: apt-get install php7.0 libapache2-mod-php7.0 -y
#############################################################################################################

#####Instalar mysql###########################


#########################################################################
  handlers:
  - name: reinicia apache
    service:
      name: apache2
      state: restarted
  - name: reiniciar mysql
    service:
      name: mysql
      state: restarted
