- name: "subir apache"
  hosts: master-node
 
  tasks:
  - name: "update"
    shell: apt-get update -y
    register: apt-atualiza

  - name: "subir-apache"    
    apt: name=apache2 state=present


  - name: "copiavhost"
    when: apt-atualiza|success
    copy:src=template/meuwebsite.conf dest=/etc/apache2/sites-enable/000-default.conf
 
  handlers:
  - name: start apache
    service: name=apache2 state=started
